# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"`\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x03\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\x12\x15\n\rlast_log_term\x18\x04 \x01(\x03\"\x94\x01\n\rAppendRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x11\n\tleader_id\x18\x02 \x01(\x03\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x03\x12\x15\n\rprev_log_term\x18\x04 \x01(\x03\x12\x1c\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0b.raft.Entry\x12\x15\n\rleader_commit\x18\x06 \x01(\x03\"4\n\x0eGetLeaderReply\x12\x11\n\tleader_id\x18\x01 \x01(\x03\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\" \n\x0eSuspendRequest\x12\x0e\n\x06period\x18\x01 \x01(\x03\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"3\n\x08SetReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0eleader_address\x18\x02 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"B\n\x08GetReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\x12\x16\n\x0eleader_address\x18\x03 \x01(\t\"1\n\x05\x45ntry\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\".\n\x0eResultWithTerm\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0e\n\x06result\x18\x02 \x01(\x08\"\x0e\n\x0c\x45mptyMessage2\xce\x02\n\x08RaftNode\x12\x38\n\x0bRequestVote\x12\x11.raft.VoteRequest\x1a\x14.raft.ResultWithTerm\"\x00\x12<\n\rAppendEntries\x12\x13.raft.AppendRequest\x1a\x14.raft.ResultWithTerm\"\x00\x12\x37\n\tGetLeader\x12\x12.raft.EmptyMessage\x1a\x14.raft.GetLeaderReply\"\x00\x12\x35\n\x07Suspend\x12\x14.raft.SuspendRequest\x1a\x12.raft.EmptyMessage\"\x00\x12,\n\x06SetVal\x12\x10.raft.SetRequest\x1a\x0e.raft.SetReply\"\x00\x12,\n\x06GetVal\x12\x10.raft.GetRequest\x1a\x0e.raft.GetReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=20
  _globals['_VOTEREQUEST']._serialized_end=116
  _globals['_APPENDREQUEST']._serialized_start=119
  _globals['_APPENDREQUEST']._serialized_end=267
  _globals['_GETLEADERREPLY']._serialized_start=269
  _globals['_GETLEADERREPLY']._serialized_end=321
  _globals['_SUSPENDREQUEST']._serialized_start=323
  _globals['_SUSPENDREQUEST']._serialized_end=355
  _globals['_SETREQUEST']._serialized_start=357
  _globals['_SETREQUEST']._serialized_end=397
  _globals['_SETREPLY']._serialized_start=399
  _globals['_SETREPLY']._serialized_end=450
  _globals['_GETREQUEST']._serialized_start=452
  _globals['_GETREQUEST']._serialized_end=477
  _globals['_GETREPLY']._serialized_start=479
  _globals['_GETREPLY']._serialized_end=545
  _globals['_ENTRY']._serialized_start=547
  _globals['_ENTRY']._serialized_end=596
  _globals['_RESULTWITHTERM']._serialized_start=598
  _globals['_RESULTWITHTERM']._serialized_end=644
  _globals['_EMPTYMESSAGE']._serialized_start=646
  _globals['_EMPTYMESSAGE']._serialized_end=660
  _globals['_RAFTNODE']._serialized_start=663
  _globals['_RAFTNODE']._serialized_end=997
# @@protoc_insertion_point(module_scope)
