# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import zab_pb2 as zab__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in zab_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ZabNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FastLeaderElection = channel.unary_unary(
                '/zab.ZabNode/FastLeaderElection',
                request_serializer=zab__pb2.FLEMessage.SerializeToString,
                response_deserializer=zab__pb2.FLEMessage.FromString,
                _registered_method=True)
        self.ProposeTransaction = channel.unary_unary(
                '/zab.ZabNode/ProposeTransaction',
                request_serializer=zab__pb2.ProposeRequest.SerializeToString,
                response_deserializer=zab__pb2.AckMessage.FromString,
                _registered_method=True)
        self.CommitTransaction = channel.unary_unary(
                '/zab.ZabNode/CommitTransaction',
                request_serializer=zab__pb2.CommitRequest.SerializeToString,
                response_deserializer=zab__pb2.EmptyMessage.FromString,
                _registered_method=True)
        self.GetLeader = channel.unary_unary(
                '/zab.ZabNode/GetLeader',
                request_serializer=zab__pb2.EmptyMessage.SerializeToString,
                response_deserializer=zab__pb2.GetLeaderReply.FromString,
                _registered_method=True)
        self.Suspend = channel.unary_unary(
                '/zab.ZabNode/Suspend',
                request_serializer=zab__pb2.SuspendRequest.SerializeToString,
                response_deserializer=zab__pb2.EmptyMessage.FromString,
                _registered_method=True)
        self.SetVal = channel.unary_unary(
                '/zab.ZabNode/SetVal',
                request_serializer=zab__pb2.SetRequest.SerializeToString,
                response_deserializer=zab__pb2.SetReply.FromString,
                _registered_method=True)
        self.GetVal = channel.unary_unary(
                '/zab.ZabNode/GetVal',
                request_serializer=zab__pb2.GetRequest.SerializeToString,
                response_deserializer=zab__pb2.GetReply.FromString,
                _registered_method=True)


class ZabNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FastLeaderElection(self, request, context):
        """Fast Leader Election
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProposeTransaction(self, request, context):
        """Transaction Processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeader(self, request, context):
        """Client Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Suspend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZabNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FastLeaderElection': grpc.unary_unary_rpc_method_handler(
                    servicer.FastLeaderElection,
                    request_deserializer=zab__pb2.FLEMessage.FromString,
                    response_serializer=zab__pb2.FLEMessage.SerializeToString,
            ),
            'ProposeTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeTransaction,
                    request_deserializer=zab__pb2.ProposeRequest.FromString,
                    response_serializer=zab__pb2.AckMessage.SerializeToString,
            ),
            'CommitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitTransaction,
                    request_deserializer=zab__pb2.CommitRequest.FromString,
                    response_serializer=zab__pb2.EmptyMessage.SerializeToString,
            ),
            'GetLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeader,
                    request_deserializer=zab__pb2.EmptyMessage.FromString,
                    response_serializer=zab__pb2.GetLeaderReply.SerializeToString,
            ),
            'Suspend': grpc.unary_unary_rpc_method_handler(
                    servicer.Suspend,
                    request_deserializer=zab__pb2.SuspendRequest.FromString,
                    response_serializer=zab__pb2.EmptyMessage.SerializeToString,
            ),
            'SetVal': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVal,
                    request_deserializer=zab__pb2.SetRequest.FromString,
                    response_serializer=zab__pb2.SetReply.SerializeToString,
            ),
            'GetVal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVal,
                    request_deserializer=zab__pb2.GetRequest.FromString,
                    response_serializer=zab__pb2.GetReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zab.ZabNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zab.ZabNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ZabNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FastLeaderElection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zab.ZabNode/FastLeaderElection',
            zab__pb2.FLEMessage.SerializeToString,
            zab__pb2.FLEMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProposeTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zab.ZabNode/ProposeTransaction',
            zab__pb2.ProposeRequest.SerializeToString,
            zab__pb2.AckMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zab.ZabNode/CommitTransaction',
            zab__pb2.CommitRequest.SerializeToString,
            zab__pb2.EmptyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zab.ZabNode/GetLeader',
            zab__pb2.EmptyMessage.SerializeToString,
            zab__pb2.GetLeaderReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Suspend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zab.ZabNode/Suspend',
            zab__pb2.SuspendRequest.SerializeToString,
            zab__pb2.EmptyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zab.ZabNode/SetVal',
            zab__pb2.SetRequest.SerializeToString,
            zab__pb2.SetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zab.ZabNode/GetVal',
            zab__pb2.GetRequest.SerializeToString,
            zab__pb2.GetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
