# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zab.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'zab.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tzab.proto\x12\x03zab\"\\\n\nFLEMessage\x12\x0f\n\x07node_id\x18\x01 \x01(\x03\x12\r\n\x05\x65poch\x18\x02 \x01(\x03\x12\x0c\n\x04zxid\x18\x03 \x01(\x03\x12\r\n\x05state\x18\x04 \x01(\t\x12\x11\n\tleader_id\x18\x05 \x01(\x03\"g\n\x0eProposeRequest\x12\r\n\x05\x65poch\x18\x01 \x01(\x03\x12\x0c\n\x04zxid\x18\x02 \x01(\x03\x12\x11\n\tleader_id\x18\x03 \x01(\x03\x12%\n\x0btransaction\x18\x04 \x01(\x0b\x32\x10.zab.Transaction\"7\n\x0bTransaction\x12\x0c\n\x04zxid\x18\x01 \x01(\x03\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\":\n\nAckMessage\x12\r\n\x05\x65poch\x18\x01 \x01(\x03\x12\x0c\n\x04zxid\x18\x02 \x01(\x03\x12\x0f\n\x07success\x18\x03 \x01(\x08\",\n\rCommitRequest\x12\r\n\x05\x65poch\x18\x01 \x01(\x03\x12\x0c\n\x04zxid\x18\x02 \x01(\x03\"4\n\x0eGetLeaderReply\x12\x11\n\tleader_id\x18\x01 \x01(\x03\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\" \n\x0eSuspendRequest\x12\x0e\n\x06period\x18\x01 \x01(\x03\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"3\n\x08SetReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0eleader_address\x18\x02 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"B\n\x08GetReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\x12\x16\n\x0eleader_address\x18\x03 \x01(\t\"\x0e\n\x0c\x45mptyMessage2\x83\x03\n\x07ZabNode\x12\x38\n\x12\x46\x61stLeaderElection\x12\x0f.zab.FLEMessage\x1a\x0f.zab.FLEMessage\"\x00\x12<\n\x12ProposeTransaction\x12\x13.zab.ProposeRequest\x1a\x0f.zab.AckMessage\"\x00\x12<\n\x11\x43ommitTransaction\x12\x12.zab.CommitRequest\x1a\x11.zab.EmptyMessage\"\x00\x12\x35\n\tGetLeader\x12\x11.zab.EmptyMessage\x1a\x13.zab.GetLeaderReply\"\x00\x12\x33\n\x07Suspend\x12\x13.zab.SuspendRequest\x1a\x11.zab.EmptyMessage\"\x00\x12*\n\x06SetVal\x12\x0f.zab.SetRequest\x1a\r.zab.SetReply\"\x00\x12*\n\x06GetVal\x12\x0f.zab.GetRequest\x1a\r.zab.GetReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zab_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLEMESSAGE']._serialized_start=18
  _globals['_FLEMESSAGE']._serialized_end=110
  _globals['_PROPOSEREQUEST']._serialized_start=112
  _globals['_PROPOSEREQUEST']._serialized_end=215
  _globals['_TRANSACTION']._serialized_start=217
  _globals['_TRANSACTION']._serialized_end=272
  _globals['_ACKMESSAGE']._serialized_start=274
  _globals['_ACKMESSAGE']._serialized_end=332
  _globals['_COMMITREQUEST']._serialized_start=334
  _globals['_COMMITREQUEST']._serialized_end=378
  _globals['_GETLEADERREPLY']._serialized_start=380
  _globals['_GETLEADERREPLY']._serialized_end=432
  _globals['_SUSPENDREQUEST']._serialized_start=434
  _globals['_SUSPENDREQUEST']._serialized_end=466
  _globals['_SETREQUEST']._serialized_start=468
  _globals['_SETREQUEST']._serialized_end=508
  _globals['_SETREPLY']._serialized_start=510
  _globals['_SETREPLY']._serialized_end=561
  _globals['_GETREQUEST']._serialized_start=563
  _globals['_GETREQUEST']._serialized_end=588
  _globals['_GETREPLY']._serialized_start=590
  _globals['_GETREPLY']._serialized_end=656
  _globals['_EMPTYMESSAGE']._serialized_start=658
  _globals['_EMPTYMESSAGE']._serialized_end=672
  _globals['_ZABNODE']._serialized_start=675
  _globals['_ZABNODE']._serialized_end=1062
# @@protoc_insertion_point(module_scope)
